= xhci_hcd-rebind
:toc:
:toc-placement!:

image:https://img.shields.io/github/license/bpetlert/xhci_hcd-rebind?style=flat-square["License: MIT",link=./LICENSE]

This software is crated to temporarily fix the error of 'USB 3.0 to ethernet adapter' on xhci_hcd bus.

.The example of error message:
[source,shell]
----
[ 1179.475926] kernel: xhci_hcd 0000:04:00.0: WARN: TRB error for slot 1 ep 5 on endpoint
[ 1179.607026] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607049] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607054] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607058] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
----

When these errors occur, the device stop functioning until reconnect or rebind.
This software will automatically detect these error messages and then rebind the device.

toc::[]

== Disclaimer

*DO NOT USE THIS SOFTWARE FOR ANY STORAGE DEVICES THAT CONNECT TO XHCI_HCD BUS.*
This software is meant for temporary solution to the problem of 'USB 3.0 to ethernet adapter' on xhci_hcd bus only.

== Installation

=== Arch Linux

To build and install arch package from GIT source:

[source,shell]
----
$ git clone https://github.com/bpetlert/xhci_hcd-rebind.git
$ cd xhci_hcd-rebind
$ makepkg -p PKGBUILD.local
$ pacman -U xhci_hcd-rebind-x.x.x.rx.gxxxxxxx-1-x86_64.pkg.tar.zst
----

Then enable/start xhci_hcd-rebind.service

[source,shell]
----
$ systemctl enable xhci_hcd-rebind.service
$ systemctl start xhci_hcd-rebind.service
----

== Configuration

The configuration is place in `/etc/systemd/xhci_hcd-rebind.toml` file.

.Example of configurations
[source,toml]
----
include::xhci_hcd-rebind.toml[]
----

The `bus-id` is required, other settings are optional.

== License

*link:./LICENSE[MIT license]*
